# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
sudo: required
dist: bionic
script:
  - cmake -H. -Bbuild && cmake --build build -- -j 4 && echo Testing && bin/test_atomicbitvector 10000000 8
